routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('home');
Route::get('/Wallpaper', 'PagesController@wallpaper')->name('wallpaper');
Route::get('/category', 'PagesController@category')->name('category');
Route::get('/Admin', 'PagesController@Admin')->name('Admin');
Route::get('/Search', 'PagesController@Search')->name('search');
Route::get('/PostSearch', 'PagesController@PostSearch')->name('PostSearch');
Route::get('/LogPage', 'PagesController@LogPage')->name('LogPage');
Route::post('/picture/{id}', 'ActionPost@PostAction');
Route::get('/UserSetting/{id}', 'PagesController@UserProfile')->name('User');
Route::post('/UserSetting/{id}', 'ActionPost@Follow')->name('follow');

Route::get('/phpinfo', function() {
    return view('phpinfo');
});

Route::resource('picture', 'PostController');
Route::resource('cat', 'CategoryController');
Route::resource('settings', 'MySettingController');

Auth::routes();

resources/views/categorie/create.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
        <h1 style="padding-bottom: 15px">Ajouter une catégorie</h1>
        @include('pages.flash')
        @include('pages.errors')
        {!! Form::open(['url' => route('cat.store')]) !!}
        <div class="form-group">
            {!! Form::label('Name') !!}
            {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => "Votre nom de catégorie", 'required' => true]) !!}
        </div>
        <button class="btn btn-primary">Envoyer</button>
    {!! Form::close() !!}
    </div>
@endsection

resources/views/categorie/edit.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
        <h1 style="padding-bottom: 15px">Ajouter une catégorie</h1>
        @include('pages.flash')
        @include('pages.errors')
        {!! Form::open(['method' => 'put', 'url' => route('cat.update', ['id' => $cat_id->id])]) !!}
        <div class="form-group">
            {!! Form::label('Name') !!}
            {!! Form::text('name', $cat_id->name, ['class' => 'form-control', 'placeholder' => "Votre nom de catégorie", 'required' => true]) !!}
        </div>
        <button class="btn btn-primary">Envoyer</button>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/categorie/show.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
        <h1>Voici les wallpapers de la catégorie "{{ $post_fetch->name }}"</h1>
        <div class="row">
            @foreach($paginator as $post)
                <div class="col-sm-4">
                    <div class="thumb-container">
                        <div class="thumb-contain">
                            <div class="boxgrip">
                                <a href="{{ route('picture.show', ['id' => $post->id])}}">
                                    <img height="250" width="350" class="" src="{{ $post->image->url_min }}" alt="Fond d'écran HD | Arrière-Plan ID:958080">
                                </a>
                            </div>
                            <div class="hover-box">
                            <span class="thumb-info-big">
						        <span>{{ $post->image->size }}</span>&nbsp;&nbsp;
						        <a href="{{ route('picture.show', ['id' => $post->id])}}" title="{{ $post->title }}">{{ $post->title }}</a>&nbsp;&nbsp;
						        <a href="{{ route('cat.show', ['id' => $post->category->id])}}" title="{{ $post->category->name }} Fonds d'écran HD | Arrière-Plans">{{ $post->category->name }}</a>
					        </span>
                            </div>
                        </div>
                        <div class="extra-block"></div>
                    </div>
                </div>
            @endforeach
        </div>
            {{ $paginator->links() }}
        </div>
    </div>
</div>
@endsection