routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('home');
Route::get('/Wallpaper', 'PagesController@wallpaper')->name('wallpaper');
Route::get('/category', 'PagesController@category')->name('category');
Route::get('/Admin', 'PagesController@Admin')->name('Admin');
Route::get('/Search', 'PagesController@Search')->name('search');
Route::get('/PostSearch', 'PagesController@PostSearch')->name('PostSearch');
Route::get('/LogPage', 'PagesController@LogPage')->name('LogPage');
Route::post('/picture/{id}', 'ActionPost@PostAction');
Route::get('/UserSetting/{id}', 'PagesController@UserProfile')->name('User');
Route::post('/UserSetting/{id}', 'ActionPost@Follow')->name('follow');

Route::get('/phpinfo', function() {
    return view('phpinfo');
});

Route::resource('picture', 'PostController');
Route::resource('cat', 'CategoryController');
Route::resource('settings', 'MySettingController');

Auth::routes();

resources/views/pages/PostOrCat.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
        @include('pages.flash')
        <h1>Admin Page</h1>
        <div class="jumbotron">
            <h1>Bienvenue sur votre Admin Page</h1>
            <p>Mais vous allez vous posez, " Quelle est cette page ?", ne paniquez pas !!! Cette page va vous permettre de modifier ou encore de suprimmer vos images et également vos catégories crée !!!</p>
        </div>
        <ul class="nav nav-tabs" id="myTabs" role="tablist">
            <li role="presentation" class="dropLi active">
                <a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Vos Images</a>
            </li>
            <li role="presentation" class="dropLi">
                <a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Vos Catégories</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade active in" role="tabpanel" id="home" aria-labelledby="home-tab">
                <div style="padding-top: 25px">
                    <a class="btn btn-primary" type="submit" href="{{ route('picture.create') }}">Ajouter une image</a>
                </div>
                <div style="padding-top: 25px">
                    <table class="table panel panel-body">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Titre</th>
                            <th>Description</th>
                            <th>Categorie</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($post as $post)
                            <tr id="id_posts">
                                <td>{{ $post->id }}</td>
                                <td>{{ $post->title }}</td>
                                <td>{{ substr($post->content, '0', '75') }} ...</td>
                                <td>{{ $post->category->name }}</td>
                                <td>
                                    <form action="">
                                        <a class="btn btn-primary" href="{{ route('picture.edit', ['id' => $post->id]) }}">Modifier</a>
                                    </form>
                                    {!! Form::open(['method' => 'DELETE', 'url' => route('picture.destroy' , ['id' => $post->id])]) !!}
                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody></table>
                </div>
            </div>
            <div class="tab-pane fade" role="tabpanel" id="profile" aria-labelledby="profile-tab">
                <div style="padding-top: 25px">
                    <a class="btn btn-primary" type="submit" href="{{ route('cat.create') }}">Ajouter une catégorie</a>
                </div>
                <div style="padding-top: 25px">
                    <table class="table panel panel-body">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Image associé</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($cat as $cat)
                            <tr id="id_cats">
                                <td>{{ $cat->id }}</td>
                                <td>{{ $cat->name }}</td>
                                <td>
                                    @if(isset($cat->images->url_original))
                                        <a class="btn btn-primary" href="{{ $cat->images->url_original }}">Voir-Ici</a>
                                    @endif
                                </td>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('cat.edit', ['id' => $cat->id]) }}">Modifier</a>
                                    {!! Form::open(['method' => 'DELETE', 'url' => route('cat.destroy' , ['id' => $cat->id])]) !!}
                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody></table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/categories.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
        <h1 class="title center">Les différentes catégories</h1>
        <div class="row" style="padding-top: 50px">
            <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
                <table class="table panel panel-body">
                    <thead>
                    <tr>
                        <th>La Catégorie</th>
                        <th>Nombre d'images issue de la catégorie</th>
                    </tr>
                    </thead>
                    <tbody>
                @foreach($category as $cat)
                    <tr id="search_20856254">
                        <td>
                            <h3>
                                <a title="{{ $cat->name }} Fonds d'écran HD | Arrière-Plans" href="{{ route('cat.show', ['id' => $cat->id]) }}">{{ $cat->name }}</a>
                            </h3>
                        </td>
                        <td>
                            <h3>{!! \App\Post::with('category')->where('category_id', $cat->id)->count('id') !!}</h3>
                        </td>
                    </tr>
                @endforeach
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/errors.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $errors)
                <li>{{ $errors }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/pages/flash.blade.php
@if(Session::has('success'))
    <div class="alert alert-success">
        {{Session::get('success')}}
    </div>
@endif
@if(Session::has('danger'))
    <div class="alert alert-danger">
        {{Session::get('danger')}}
    </div>
@endif

resources/views/pages/index.blade.php
@extends('default')

@section('content')

<div class="container" style="padding-top: 25px">
<div class="page-header" id="banner">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <h1 id="containers">Wallpaper</h1>
                    @include('pages.flash')
                    @include('pages.errors')
                </div>
                <div class="bs-component">
                    <div class="jumbotron">
                        <h1>Bienvenue</h1>
                        <p>Bien le bonjour chez visiteur, sur ce site tu pourras trouver un tas de wallpaper, fais toi plaisir !!!</p>
                        @guest
                            <p><a class="btn btn-primary btn-lg" href="{{ route('register') }}">S'inscrire</a></p>
                        @else
                            <p><a class="btn btn-primary btn-lg" href="{{ route('picture.create') }}">Ajouter une image</a></p>
                        @endguest
                    </div>
                    <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div></div>
            </div>
        </div>
    </div>
    <h1>Les Dernières photos !!!</h1>
    <div class="row">
        @foreach($post as $post)
            <div class="col-sm-4">
                <div class="thumb-container">
                    <div class="thumb-contain">
                        <div class="boxgrip">
                            <a href="{{ route('picture.show', ['id' => $post->id])}}">
                                <img height="250" width="350" class="" src="{{ $post->image->url_min }}" alt="Fond d'écran HD | Arrière-Plan ID:958080">
                            </a>
                        </div>
                        <div class="hover-box">
                            <span class="thumb-info-big">
						        <span>5120x2880</span>&nbsp;&nbsp;
						        <a href="{{ route('picture.show', ['id' => $post->id])}}" title="{{ $post->title }}">{{ $post->title }}</a>&nbsp;&nbsp;
						        <a href="{{ route('cat.show', ['id' => $post->category->id])}}" title="{{ $post->category->name }} Fonds d'écran HD | Arrière-Plans">{{ $post->category->name }}</a>
					        </span>
                        </div>
                    </div>
                    <div class="extra-block"></div>
                </div>
            </div>
        @endforeach
    </div>
    </div>
@endsection

resources/views/pages/search.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
        @if(isset($search))
            <h1 class="center title"><i>{{ $post }}</i> Fonds d'écran: {{ $search }}</h1>
        @endif
        @if(!isset($search))
            <h1 class="center title">Aucuns Wallpapers trouvés</h1>
        @endif
        @include('pages.flash')
        @include('pages.errors')
        <div class="row">
            @if(isset($paginator))
            @foreach($paginator as $post)
                <div class="col-sm-4">
                    <div class="thumb-container">
                        <div class="thumb-contain">
                            <div class="boxgrip">
                                <a href="{{ route('picture.show', ['id' => $post->id])}}">
                                    <img height="250" width="350" class="" src="{{ $post->image->url_min }}" alt="Fond d'écran HD | Arrière-Plan ID:958080">
                                </a>
                            </div>
                            <div class="hover-box">
                            <span class="thumb-info-big">
						        <span>{{ $post->image->size }}</span>&nbsp;&nbsp;
						        <a href="{{ route('picture.show', ['id' => $post->id])}}" title="{{ $post->title }}">{{ $post->title }}</a>&nbsp;&nbsp;
						        <a href="{{ route('cat.show', ['id' => $post->category->id])}}" title="{{ $post->category->name }} Fonds d'écran HD | Arrière-Plans">{{ $post->category->name }}</a>
					        </span>
                            </div>
                        </div>
                        <div class="extra-block"></div>
                    </div>
                </div>
            @endforeach
        </div>
        {{ $paginator->links() }}
            @endif
    </div>
@endsection

resources/views/pages/wallpaper.blade.php
@extends('default')

@section('content')
    <div class="container" style="padding-top: 75px">
    <h1>Ici vous pouvez trouver plus 500 wallpapers !!!</h1>
        @include('pages.flash')
        @include('pages.errors')
        {!! Form::open(['method' => 'get', 'url' => route('search')]) !!}
        <div class="input-group" id="search_zone_index">
                <input name="search" class="search-bar form-control input-lg" placeholder="Rechercher un Fond d'écran" type="text">
                @csrf
                <span class="input-group-btn">
                <button type="submit" class="btn-search-bar btn btn-default btn-lg">
                    <span class="glyphicon">
                        <i class="fa fa-search"></i>
                    </span>
                </button>
                </span>
            </div>
        {!! Form::close() !!}
        <h4 class="center">Rechercher des Fonds d'écran! Un Fond d'écran de Jeux Vidéo, de Dragon, ...</h4>
        <div class="list-group" style="padding-top: 15px">
            <div class="list-group-item list-group-item-info">Recherches par Catégories</div>
            @foreach($category as $cat)
                <a class="list-group-item" title="{{ $cat->name }} Fonds d'écran HD | Arrière-Plans - Wallpaper Abyss" href="{{ route('cat.show', ['id' => $cat->id]) }}">{{ $cat->name }}</a>
            @endforeach
            <a class="list-group-item list-group-item-success" href="{{ route('cat.index') }}">Voir toutes les Catégories</a>
            </div>
    <div class="row">
        @foreach($paginator as $post)
            <div class="col-sm-4">
                <div class="thumb-container">
                    <div class="thumb-contain">
                        <div class="boxgrip">
                            <a href="{{ route('picture.show', ['id' => $post->id])}}">
                                <img height="250" width="350" class="" src="{{ $post->image->url_min }}" alt="Fond d'écran HD | Arrière-Plan ID:958080">
                            </a>
                        </div>
                        <div class="hover-box">
                            <span class="thumb-info-big">
						        <span>{{ $post->image->size }}</span>&nbsp;&nbsp;
						        <a href="{{ route('picture.show', ['id' => $post->id])}}" title="{{ $post->title }}">{{ $post->title }}</a>&nbsp;&nbsp;
						        <a href="{{ route('cat.show', ['id' => $post->category->id])}}" title="{{ $post->category->name }} Fonds d'écran HD | Arrière-Plans">{{ $post->category->name }}</a>
					        </span>
                        </div>
                    </div>
                    <div class="extra-block"></div>
                </div>
            </div>
        @endforeach
    </div>
        {{ $paginator->links() }}
    </div>
@endsection